### ISSUE TITLE
[Bug]: no data connection to EB3A since new Firmware update

### ISSUE THREAD

**Issue by GammaPotato** [Patrick762/hassio-bluetti-bt#83] opened 2024-03-31 18:28 UTC
### What happened?

No data connection since i updated my EB3A. All stats are unknown. i only can add the EB3A but no data gets loaded. 

integration Version 0.0.21

ARM: v2063,03
DSP: v2052,11

what i tried

Soft Reboot
Hard Reboot
Integration Reinstall (remove device -> Uninstall -> Reboot -> Install -> Reboot -> adding device works but no data
Swtich From Internal BT to BT dongle and back

i cant provied any Debug. Debug issnt working

### Version

0.0.17

### What device are you seeing the problem on?

EB3A

### What bluetooth connection are you using?

USB dongle

### Have you changed the integration settings?

false

### Relevant log output

```shell
2024-03-31 20:24:27.925 ERROR (MainThread) [custom_components.bluetti_bt.bluetti_bt_lib.bluetooth.device_reader] Polling timed out
2024-03-31 20:24:27.927 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXdc_input_power
2024-03-31 20:24:27.928 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXac_input_power
2024-03-31 20:24:27.928 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXac_output_power
2024-03-31 20:24:27.929 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXdc_output_power
2024-03-31 20:24:27.929 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXtotal_power_generation
2024-03-31 20:24:27.930 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXtotal_battery_percent
2024-03-31 20:24:27.930 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXac_input_voltage
2024-03-31 20:24:27.930 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXinternal_dc_input_voltage
2024-03-31 20:24:27.931 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXled_mode
2024-03-31 20:24:27.932 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXeco_shutdown
2024-03-31 20:24:27.933 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for eb3a23XXXXXXXXXXcharging_mode
2024-03-31 20:24:27.934 ERROR (MainThread) [custom_components.bluetti_bt.switch] Invalid data from coordinator (switch.eb3a23XXXXXXXXXXac_output)
2024-03-31 20:24:27.934 ERROR (MainThread) [custom_components.bluetti_bt.switch] Invalid data from coordinator (switch.eb3a23XXXXXXXXXXdc_output)
2024-03-31 20:24:27.935 ERROR (MainThread) [custom_components.bluetti_bt.switch] Invalid data from coordinator (switch.eb3a23XXXXXXXXXXpower_off)
2024-03-31 20:24:27.936 ERROR (MainThread) [custom_components.bluetti_bt.switch] Invalid data from coordinator (switch.eb3a23XXXXXXXXXXeco_mode)
2024-03-31 20:24:27.936 ERROR (MainThread) [custom_components.bluetti_bt.switch] Invalid data from coordinator (switch.eb3a23XXXXXXXXXXpower_lifting)
```

**Comment by Patrick762** [comment] 2024-03-31 18:38
Thanks for the info. I'll look into it

**Comment by GammaPotato** [comment] 2024-03-31 18:41
@Patrick762 no problem. tell me if there is any new update for the integration. i need my system for the EB3A. it controlls one of my cooling systems for a spezial thing that i build

**Comment by Patrick762** [comment] 2024-03-31 18:41
I can't even connect my phone with the eb3a after the update ...

**Comment by Patrick762** [comment] 2024-03-31 18:44
And the station is now at 35% instead of 100% SoC

**Comment by GammaPotato** [comment] 2024-03-31 18:45
got same issue. just let it turn of the display and then connect again. my battery got from 45 to 35. idk what happend here

**Comment by Patrick762** [comment] 2024-03-31 18:46
Seems like there was a bug in the ARM Firmware Update. I only did this. Not the other one

**Comment by Patrick762** [comment] 2024-03-31 18:47
"Never change a running system"

**Comment by GammaPotato** [comment] 2024-03-31 18:48
i updaed ARM and DSP without any Probs. 

> "Never change a running system"

i wait for the fix on solar charge issue. this should it be.

**Comment by Patrick762** [comment] 2024-03-31 18:57
Got some data in HA with the preconfigured instance.

After a full restart, all the values are available again (with newly setup instance).

**Comment by GammaPotato** [comment] 2024-03-31 18:59
i still get not data with new instance. i had a preconfigured before. didnt work to.

**Comment by GammaPotato** [comment] 2024-03-31 19:00
![chrome_Yveat8IUZw](https://github.com/Patrick762/hassio-bluetti-bt/assets/69405733/25c52187-1daa-4b9f-94f3-a0d50c23dedf)
i started charging and have an input off 265w and output of 9 w. still no data after couple minutes

**Comment by GammaPotato** [comment] 2024-03-31 19:11
did a full reboot. no data. Get the same log as above. all Outputs are on and Display is on. 
![chrome_YQJlTsfnc0](https://github.com/Patrick762/hassio-bluetti-bt/assets/69405733/0ce866ce-aa92-423f-8cd5-07c5d3a34511)

the entity is not numeric

**Comment by Patrick762** [comment] 2024-03-31 19:33
Just to check this: Do you have your Bluetti App open on your phone (had the same problem right now, even if the phone was in standby)

**Comment by GammaPotato** [comment] 2024-03-31 19:34
> Just to check this: Do you have your Bluetti App open on your phone (had the same problem right now, even if the phone was in standby)

nope. force closed bluetti App

**Comment by Patrick762** [comment] 2024-03-31 19:39
I can't reproduce this issue currently.
Do you have a bluetooth proxy to test if it is a BT dongle problem?

**Comment by GammaPotato** [comment] 2024-03-31 19:42
> I can't reproduce this issue currently. Do you have a bluetooth proxy to test if it is a BT dongle problem?

ah no sorry. i tested with internal bt from my rasphberry and usb dongle. what software did u use to read the EB3A? ill try if i can get any data

**Comment by GammaPotato** [comment] 2024-03-31 19:45
@Patrick762 new text on log!

```
2024-03-31 21:44:55.716 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Pause on PRI/Upgrade:
    b''
      ^
      ```

**Comment by Patrick762** [comment] 2024-03-31 19:48
> > I can't reproduce this issue currently. Do you have a bluetooth proxy to test if it is a BT dongle problem?
> 
> ah no sorry. i tested with internal bt from my rasphberry and usb dongle. what software did u use to read the EB3A? ill try if i can get any data
> 
> EDIT 8 Other bt devices working perfect

I always use the ESPHome Bluetooth Proxy Firmware with M5Stack AtomU

**Comment by GammaPotato** [comment] 2024-03-31 19:49
> > > I can't reproduce this issue currently. Do you have a bluetooth proxy to test if it is a BT dongle problem?
> > 
> > 
> > ah no sorry. i tested with internal bt from my rasphberry and usb dongle. what software did u use to read the EB3A? ill try if i can get any data
> > EDIT 8 Other bt devices working perfect
> 
> I always use the ESPHome Bluetooth Proxy Firmware with M5Stack AtomU

i need to buy a ESPHome first.

**Comment by Patrick762** [comment] 2024-03-31 19:51
If I can reproduce the issue in the next few days I'll look into it

**Comment by Patrick762** [comment] 2024-03-31 19:53
You can also join the new discord server to contact me: https://discord.gg/nqcgV2MW

**Comment by GammaPotato** [comment] 2024-03-31 19:55
> You can also join the new discord server to contact me (maybe it's easier to solve this in german): https://discord.gg/nqcgV2MW

Very good idea! im in!

**Comment by Patrick762** [comment] 2024-05-30 10:42
seems resolved. Closing issue for now

**Closed by Patrick762** 2024-05-30 10:42 UTC
Labels: bug
