### ISSUE TITLE
Tried version 0.0.11 and beta 0.0.22 not possible make integration in home assistant[Bug]: 

### ISSUE THREAD

**Issue by polpas** [Patrick762/hassio-bluetti-bt#92] opened 2024-04-08 16:03 UTC
### What happened?

hassio-bluetti-bt is not being integrated after intsalling over hacs. I also tried mannualy adding the files but without success.

### Version

0.0.11

### What device are you seeing the problem on?

AC200M

### What bluetooth connection are you using?

ESPHome bluetooth proxy

### Have you changed the integration settings?

false

### Relevant log output

```shell
Hassio bluetti bt pops up a windows without ending the integration
```

**Comment by Patrick762** [comment] 2024-04-08 18:03
The first connection can take longer (I saw 2 minutes as maximum)

**Comment by Patrick762** [comment] 2024-05-31 06:27
Might be a duplicate of #89

**Comment by Patrick762** [comment] 2024-05-31 15:23
@polpas Can you please test Release 0.1 to check if this issue still exists?

**Comment by polpas** [comment] 2024-05-31 15:41
Thank you for your time. I had to try another way of implementation. At this moment I'm using Bluetti to MQTT

**Closed** 2024-05-31 17:48 UTC
Labels: bug
