### ISSUE TITLE
AC500+2B300S difference  between 0.0.16 and 0.0.20 

### ISSUE THREAD

**Issue by ItsMe00007** [Patrick762/hassio-bluetti-bt#76] opened 2024-03-16 14:37 UTC
There are quite some sensors which don't work anymore or show wrong values after updating from 0.0.16 to 0.0.20.
I thought you were just adding new Powerstations and the working ones don't get changed, but it seems you changed a lot.

First: how it looked with 0.0.16:
<img width="315" alt="Result1 AC500 and 2xB300S Bluetti BT 0 0 16" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/485f946e-e402-4322-8426-f9b952d19d7e">
<img width="315" alt="Result2 AC500 and 2xB300S Bluetti BT 0 0 16" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/bed518d4-a79b-4fcb-8b3f-1fc1bfe2b932">

And with 0.0.20:
1. AC DC output controls: you can't really see if they are on or off, the 0.0.16 way showed it clearly
2. AC Input Frequency is now "unknown"
3. AC Output mode only shows numbers, no text.
4. Battery Range start/End is missing.
5. Grid charge is now "unknown"
6. internal AC Frequency is 500Hz instead of 50Hz
7. internal AC Voltage is 2288V instead of 228,8V
8. Split phase machine type ist "unknown"
9. Time Control is "unknown"
10. UPS Working mode is "unknown"
11. Battery Pack 1 and 2 Infos are "unavailable"

<img width="315" alt="Result1 AC500 and 2xB300S Bluetti BT 0 0 20" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/fd35ce8e-1eb9-4ad5-a90b-65065aab89c1">
<img width="315" alt="Result2 AC500 and 2xB300S Bluetti BT 0 0 20" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/ce6e9cf9-cbc5-4fdd-ace2-d2c321e4b65f">

**Comment by Patrick762** [comment] 2024-03-16 15:02
I changed the base for the integration so it has a smaller footprint in total, but might have missed some parts. I'll look into it

**Comment by Patrick762** [comment] 2024-03-16 15:35
FYI I those are the things I was missing:

1. Added register polling for those addresses
2. Added register polling for this address
3. Not changed, should already work
4. Added register polling for those addresses
5. Added register polling for this address
6. Changed scaling
7. Changed scaling
8. Added register polling for this address
9. Added register polling for this address
10. Added register polling for this address
11. Removed addresses from normal polling (now it's pack polling only)

**Comment by Patrick762** [comment] 2024-03-16 15:59
Changes are now in Pull Request #77

**Comment by Patrick762** [comment] 2024-03-16 16:48
Looks like Enums now work as expected

![Screenshot 2024-03-16 at 17-47-47 Einstellungen – Home Assistant](https://github.com/Patrick762/hassio-bluetti-bt/assets/80690443/a14ed992-b120-4bf8-bf4c-b41b4e44df4e)

**Comment by Patrick762** [comment] 2024-03-16 17:00
@ItsMe00007 New version is now available: 0.0.21

**Comment by ItsMe00007** [comment] 2024-03-16 19:10
Hi Patrick,
wow, that was really fast !!!!
Looks much better now.

Only the Battery Pack 1 and 2 are "unavailable". They were working in 0.0.16.

<img width="315" alt="Bildschirmfoto 2024-03-16 um 20 07 29" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/1009b44c-59f9-4d6b-b7da-94ee67aac0de">

**Comment by Patrick762** [comment] 2024-03-16 19:17
Pack polling takes around 5 seconds per pack.

If I have some time tomorrow I'll test the latest version on an AC300 (very similar)

**Comment by danrichardson** [comment] 2024-03-27 19:53
I can confirm that the battery pack values are not present on my AC300 0.0.21 as well.

**Comment by ItsMe00007** [comment] 2024-04-01 10:53
AC500+2xB300S: Current status with 0.0.21:

1. Battery Pack Info is ok in 0.0.16, but unavailable in 0.0.21.

2. All 3 DC Internal Inputs have wrong scaling factor:
Voltage: should be 90,1 instead of 901
Power: should be 303 instead of 30,3
Current: should be 3,3 instead of 0,33

Then it would match the Power/Voltage/Current from PV Input 1 (currently measured externally)

**Comment by Patrick762** [comment] 2024-04-01 12:10
@ItsMe00007 This should fix the pack polling: https://github.com/Patrick762/hassio-bluetti-bt/pull/87/files
I'll release the new version later

**Comment by ItsMe00007** [comment] 2024-04-01 12:59
> @ItsMe00007 Can you tell me which entity names you mean in 2.?

I mean these entities:
<img width="309" alt="Bildschirmfoto 2024-04-01 um 14 58 05" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/0befd706-eba6-494a-9940-77b6e2fdf8af">

**Comment by ItsMe00007** [comment] 2024-04-01 13:08
I just tested the new 0.0.22:
AC500 Battery Pack info is still "unavailable"

<img width="308" alt="Bildschirmfoto 2024-04-01 um 15 05 38" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/76f2709f-f7c4-460c-a6d2-052983f3a18a">

**Comment by ItsMe00007** [comment] 2024-05-06 13:49
I just tested the new 0.0.23:

AC500 Battery Pack info is still "unavailable", the latest Version where it worked was 0.0.16.
I have automations which depend on these values, therefore I had to go o 0.0.16.

Any chance to get that fixed ?

<img width="301" alt="Bildschirmfoto 2024-05-06 um 07 54 52" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/7f86fa63-6631-4d81-9204-942e54a98039">

**Comment by Patrick762** [comment] 2024-05-31 15:24
Should be fixed in Release 0.1

**Closed by Patrick762** 2024-05-31 15:24 UTC
Labels: bug, verified bug
